// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class Villas extends Table with TableInfo<Villas, VillasData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Villas(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> location = GeneratedColumn<String>(
    'location',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<String> ownerName = GeneratedColumn<String>(
    'owner_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<String> ownerContact = GeneratedColumn<String>(
    'owner_contact',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<int> isActive = GeneratedColumn<int>(
    'is_active',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1))',
    defaultValue: const CustomExpression('1'),
  );
  late final GeneratedColumn<String> description = GeneratedColumn<String>(
    'description',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<String> uniqueSellingPoints =
      GeneratedColumn<String>(
        'unique_selling_points',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NOT NULL DEFAULT \'[]\'',
        defaultValue: const CustomExpression('\'[]\''),
      );
  late final GeneratedColumn<String> amenities = GeneratedColumn<String>(
    'amenities',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'[]\'',
    defaultValue: const CustomExpression('\'[]\''),
  );
  late final GeneratedColumn<String> houseRules = GeneratedColumn<String>(
    'house_rules',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<int> priceWeekday = GeneratedColumn<int>(
    'price_weekday',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> priceWeekend = GeneratedColumn<int>(
    'price_weekend',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> priceHighSeason = GeneratedColumn<int>(
    'price_high_season',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<double> commissionPercent =
      GeneratedColumn<double>(
        'commission_percent',
        aliasedName,
        false,
        type: DriftSqlType.double,
        requiredDuringInsert: false,
        $customConstraints: 'NOT NULL DEFAULT 0.0',
        defaultValue: const CustomExpression('0.0'),
      );
  late final GeneratedColumn<String> privateNotes = GeneratedColumn<String>(
    'private_notes',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> updatedAt = GeneratedColumn<int>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    name,
    location,
    ownerName,
    ownerContact,
    isActive,
    description,
    uniqueSellingPoints,
    amenities,
    houseRules,
    priceWeekday,
    priceWeekend,
    priceHighSeason,
    commissionPercent,
    privateNotes,
    createdAt,
    updatedAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'villas';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  VillasData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return VillasData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      name: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}name'],
      )!,
      location: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}location'],
      )!,
      ownerName: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}owner_name'],
      )!,
      ownerContact: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}owner_contact'],
      )!,
      isActive: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}is_active'],
      )!,
      description: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}description'],
      )!,
      uniqueSellingPoints: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}unique_selling_points'],
      )!,
      amenities: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}amenities'],
      )!,
      houseRules: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}house_rules'],
      )!,
      priceWeekday: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}price_weekday'],
      )!,
      priceWeekend: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}price_weekend'],
      )!,
      priceHighSeason: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}price_high_season'],
      )!,
      commissionPercent: attachedDatabase.typeMapping.read(
        DriftSqlType.double,
        data['${effectivePrefix}commission_percent'],
      )!,
      privateNotes: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}private_notes'],
      )!,
      createdAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at'],
      )!,
      updatedAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}updated_at'],
      )!,
    );
  }

  @override
  Villas createAlias(String alias) {
    return Villas(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class VillasData extends DataClass implements Insertable<VillasData> {
  final String id;
  final String name;
  final String location;
  final String ownerName;
  final String ownerContact;
  final int isActive;
  final String description;
  final String uniqueSellingPoints;
  final String amenities;
  final String houseRules;
  final int priceWeekday;
  final int priceWeekend;
  final int priceHighSeason;
  final double commissionPercent;
  final String privateNotes;
  final int createdAt;
  final int updatedAt;
  const VillasData({
    required this.id,
    required this.name,
    required this.location,
    required this.ownerName,
    required this.ownerContact,
    required this.isActive,
    required this.description,
    required this.uniqueSellingPoints,
    required this.amenities,
    required this.houseRules,
    required this.priceWeekday,
    required this.priceWeekend,
    required this.priceHighSeason,
    required this.commissionPercent,
    required this.privateNotes,
    required this.createdAt,
    required this.updatedAt,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['name'] = Variable<String>(name);
    map['location'] = Variable<String>(location);
    map['owner_name'] = Variable<String>(ownerName);
    map['owner_contact'] = Variable<String>(ownerContact);
    map['is_active'] = Variable<int>(isActive);
    map['description'] = Variable<String>(description);
    map['unique_selling_points'] = Variable<String>(uniqueSellingPoints);
    map['amenities'] = Variable<String>(amenities);
    map['house_rules'] = Variable<String>(houseRules);
    map['price_weekday'] = Variable<int>(priceWeekday);
    map['price_weekend'] = Variable<int>(priceWeekend);
    map['price_high_season'] = Variable<int>(priceHighSeason);
    map['commission_percent'] = Variable<double>(commissionPercent);
    map['private_notes'] = Variable<String>(privateNotes);
    map['created_at'] = Variable<int>(createdAt);
    map['updated_at'] = Variable<int>(updatedAt);
    return map;
  }

  VillasCompanion toCompanion(bool nullToAbsent) {
    return VillasCompanion(
      id: Value(id),
      name: Value(name),
      location: Value(location),
      ownerName: Value(ownerName),
      ownerContact: Value(ownerContact),
      isActive: Value(isActive),
      description: Value(description),
      uniqueSellingPoints: Value(uniqueSellingPoints),
      amenities: Value(amenities),
      houseRules: Value(houseRules),
      priceWeekday: Value(priceWeekday),
      priceWeekend: Value(priceWeekend),
      priceHighSeason: Value(priceHighSeason),
      commissionPercent: Value(commissionPercent),
      privateNotes: Value(privateNotes),
      createdAt: Value(createdAt),
      updatedAt: Value(updatedAt),
    );
  }

  factory VillasData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return VillasData(
      id: serializer.fromJson<String>(json['id']),
      name: serializer.fromJson<String>(json['name']),
      location: serializer.fromJson<String>(json['location']),
      ownerName: serializer.fromJson<String>(json['ownerName']),
      ownerContact: serializer.fromJson<String>(json['ownerContact']),
      isActive: serializer.fromJson<int>(json['isActive']),
      description: serializer.fromJson<String>(json['description']),
      uniqueSellingPoints: serializer.fromJson<String>(
        json['uniqueSellingPoints'],
      ),
      amenities: serializer.fromJson<String>(json['amenities']),
      houseRules: serializer.fromJson<String>(json['houseRules']),
      priceWeekday: serializer.fromJson<int>(json['priceWeekday']),
      priceWeekend: serializer.fromJson<int>(json['priceWeekend']),
      priceHighSeason: serializer.fromJson<int>(json['priceHighSeason']),
      commissionPercent: serializer.fromJson<double>(json['commissionPercent']),
      privateNotes: serializer.fromJson<String>(json['privateNotes']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
      updatedAt: serializer.fromJson<int>(json['updatedAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'name': serializer.toJson<String>(name),
      'location': serializer.toJson<String>(location),
      'ownerName': serializer.toJson<String>(ownerName),
      'ownerContact': serializer.toJson<String>(ownerContact),
      'isActive': serializer.toJson<int>(isActive),
      'description': serializer.toJson<String>(description),
      'uniqueSellingPoints': serializer.toJson<String>(uniqueSellingPoints),
      'amenities': serializer.toJson<String>(amenities),
      'houseRules': serializer.toJson<String>(houseRules),
      'priceWeekday': serializer.toJson<int>(priceWeekday),
      'priceWeekend': serializer.toJson<int>(priceWeekend),
      'priceHighSeason': serializer.toJson<int>(priceHighSeason),
      'commissionPercent': serializer.toJson<double>(commissionPercent),
      'privateNotes': serializer.toJson<String>(privateNotes),
      'createdAt': serializer.toJson<int>(createdAt),
      'updatedAt': serializer.toJson<int>(updatedAt),
    };
  }

  VillasData copyWith({
    String? id,
    String? name,
    String? location,
    String? ownerName,
    String? ownerContact,
    int? isActive,
    String? description,
    String? uniqueSellingPoints,
    String? amenities,
    String? houseRules,
    int? priceWeekday,
    int? priceWeekend,
    int? priceHighSeason,
    double? commissionPercent,
    String? privateNotes,
    int? createdAt,
    int? updatedAt,
  }) => VillasData(
    id: id ?? this.id,
    name: name ?? this.name,
    location: location ?? this.location,
    ownerName: ownerName ?? this.ownerName,
    ownerContact: ownerContact ?? this.ownerContact,
    isActive: isActive ?? this.isActive,
    description: description ?? this.description,
    uniqueSellingPoints: uniqueSellingPoints ?? this.uniqueSellingPoints,
    amenities: amenities ?? this.amenities,
    houseRules: houseRules ?? this.houseRules,
    priceWeekday: priceWeekday ?? this.priceWeekday,
    priceWeekend: priceWeekend ?? this.priceWeekend,
    priceHighSeason: priceHighSeason ?? this.priceHighSeason,
    commissionPercent: commissionPercent ?? this.commissionPercent,
    privateNotes: privateNotes ?? this.privateNotes,
    createdAt: createdAt ?? this.createdAt,
    updatedAt: updatedAt ?? this.updatedAt,
  );
  VillasData copyWithCompanion(VillasCompanion data) {
    return VillasData(
      id: data.id.present ? data.id.value : this.id,
      name: data.name.present ? data.name.value : this.name,
      location: data.location.present ? data.location.value : this.location,
      ownerName: data.ownerName.present ? data.ownerName.value : this.ownerName,
      ownerContact: data.ownerContact.present
          ? data.ownerContact.value
          : this.ownerContact,
      isActive: data.isActive.present ? data.isActive.value : this.isActive,
      description: data.description.present
          ? data.description.value
          : this.description,
      uniqueSellingPoints: data.uniqueSellingPoints.present
          ? data.uniqueSellingPoints.value
          : this.uniqueSellingPoints,
      amenities: data.amenities.present ? data.amenities.value : this.amenities,
      houseRules: data.houseRules.present
          ? data.houseRules.value
          : this.houseRules,
      priceWeekday: data.priceWeekday.present
          ? data.priceWeekday.value
          : this.priceWeekday,
      priceWeekend: data.priceWeekend.present
          ? data.priceWeekend.value
          : this.priceWeekend,
      priceHighSeason: data.priceHighSeason.present
          ? data.priceHighSeason.value
          : this.priceHighSeason,
      commissionPercent: data.commissionPercent.present
          ? data.commissionPercent.value
          : this.commissionPercent,
      privateNotes: data.privateNotes.present
          ? data.privateNotes.value
          : this.privateNotes,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
      updatedAt: data.updatedAt.present ? data.updatedAt.value : this.updatedAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('VillasData(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('location: $location, ')
          ..write('ownerName: $ownerName, ')
          ..write('ownerContact: $ownerContact, ')
          ..write('isActive: $isActive, ')
          ..write('description: $description, ')
          ..write('uniqueSellingPoints: $uniqueSellingPoints, ')
          ..write('amenities: $amenities, ')
          ..write('houseRules: $houseRules, ')
          ..write('priceWeekday: $priceWeekday, ')
          ..write('priceWeekend: $priceWeekend, ')
          ..write('priceHighSeason: $priceHighSeason, ')
          ..write('commissionPercent: $commissionPercent, ')
          ..write('privateNotes: $privateNotes, ')
          ..write('createdAt: $createdAt, ')
          ..write('updatedAt: $updatedAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    name,
    location,
    ownerName,
    ownerContact,
    isActive,
    description,
    uniqueSellingPoints,
    amenities,
    houseRules,
    priceWeekday,
    priceWeekend,
    priceHighSeason,
    commissionPercent,
    privateNotes,
    createdAt,
    updatedAt,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is VillasData &&
          other.id == this.id &&
          other.name == this.name &&
          other.location == this.location &&
          other.ownerName == this.ownerName &&
          other.ownerContact == this.ownerContact &&
          other.isActive == this.isActive &&
          other.description == this.description &&
          other.uniqueSellingPoints == this.uniqueSellingPoints &&
          other.amenities == this.amenities &&
          other.houseRules == this.houseRules &&
          other.priceWeekday == this.priceWeekday &&
          other.priceWeekend == this.priceWeekend &&
          other.priceHighSeason == this.priceHighSeason &&
          other.commissionPercent == this.commissionPercent &&
          other.privateNotes == this.privateNotes &&
          other.createdAt == this.createdAt &&
          other.updatedAt == this.updatedAt);
}

class VillasCompanion extends UpdateCompanion<VillasData> {
  final Value<String> id;
  final Value<String> name;
  final Value<String> location;
  final Value<String> ownerName;
  final Value<String> ownerContact;
  final Value<int> isActive;
  final Value<String> description;
  final Value<String> uniqueSellingPoints;
  final Value<String> amenities;
  final Value<String> houseRules;
  final Value<int> priceWeekday;
  final Value<int> priceWeekend;
  final Value<int> priceHighSeason;
  final Value<double> commissionPercent;
  final Value<String> privateNotes;
  final Value<int> createdAt;
  final Value<int> updatedAt;
  final Value<int> rowid;
  const VillasCompanion({
    this.id = const Value.absent(),
    this.name = const Value.absent(),
    this.location = const Value.absent(),
    this.ownerName = const Value.absent(),
    this.ownerContact = const Value.absent(),
    this.isActive = const Value.absent(),
    this.description = const Value.absent(),
    this.uniqueSellingPoints = const Value.absent(),
    this.amenities = const Value.absent(),
    this.houseRules = const Value.absent(),
    this.priceWeekday = const Value.absent(),
    this.priceWeekend = const Value.absent(),
    this.priceHighSeason = const Value.absent(),
    this.commissionPercent = const Value.absent(),
    this.privateNotes = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.updatedAt = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  VillasCompanion.insert({
    required String id,
    required String name,
    this.location = const Value.absent(),
    this.ownerName = const Value.absent(),
    this.ownerContact = const Value.absent(),
    this.isActive = const Value.absent(),
    this.description = const Value.absent(),
    this.uniqueSellingPoints = const Value.absent(),
    this.amenities = const Value.absent(),
    this.houseRules = const Value.absent(),
    this.priceWeekday = const Value.absent(),
    this.priceWeekend = const Value.absent(),
    this.priceHighSeason = const Value.absent(),
    this.commissionPercent = const Value.absent(),
    this.privateNotes = const Value.absent(),
    required int createdAt,
    required int updatedAt,
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       name = Value(name),
       createdAt = Value(createdAt),
       updatedAt = Value(updatedAt);
  static Insertable<VillasData> custom({
    Expression<String>? id,
    Expression<String>? name,
    Expression<String>? location,
    Expression<String>? ownerName,
    Expression<String>? ownerContact,
    Expression<int>? isActive,
    Expression<String>? description,
    Expression<String>? uniqueSellingPoints,
    Expression<String>? amenities,
    Expression<String>? houseRules,
    Expression<int>? priceWeekday,
    Expression<int>? priceWeekend,
    Expression<int>? priceHighSeason,
    Expression<double>? commissionPercent,
    Expression<String>? privateNotes,
    Expression<int>? createdAt,
    Expression<int>? updatedAt,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (location != null) 'location': location,
      if (ownerName != null) 'owner_name': ownerName,
      if (ownerContact != null) 'owner_contact': ownerContact,
      if (isActive != null) 'is_active': isActive,
      if (description != null) 'description': description,
      if (uniqueSellingPoints != null)
        'unique_selling_points': uniqueSellingPoints,
      if (amenities != null) 'amenities': amenities,
      if (houseRules != null) 'house_rules': houseRules,
      if (priceWeekday != null) 'price_weekday': priceWeekday,
      if (priceWeekend != null) 'price_weekend': priceWeekend,
      if (priceHighSeason != null) 'price_high_season': priceHighSeason,
      if (commissionPercent != null) 'commission_percent': commissionPercent,
      if (privateNotes != null) 'private_notes': privateNotes,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
      if (rowid != null) 'rowid': rowid,
    });
  }

  VillasCompanion copyWith({
    Value<String>? id,
    Value<String>? name,
    Value<String>? location,
    Value<String>? ownerName,
    Value<String>? ownerContact,
    Value<int>? isActive,
    Value<String>? description,
    Value<String>? uniqueSellingPoints,
    Value<String>? amenities,
    Value<String>? houseRules,
    Value<int>? priceWeekday,
    Value<int>? priceWeekend,
    Value<int>? priceHighSeason,
    Value<double>? commissionPercent,
    Value<String>? privateNotes,
    Value<int>? createdAt,
    Value<int>? updatedAt,
    Value<int>? rowid,
  }) {
    return VillasCompanion(
      id: id ?? this.id,
      name: name ?? this.name,
      location: location ?? this.location,
      ownerName: ownerName ?? this.ownerName,
      ownerContact: ownerContact ?? this.ownerContact,
      isActive: isActive ?? this.isActive,
      description: description ?? this.description,
      uniqueSellingPoints: uniqueSellingPoints ?? this.uniqueSellingPoints,
      amenities: amenities ?? this.amenities,
      houseRules: houseRules ?? this.houseRules,
      priceWeekday: priceWeekday ?? this.priceWeekday,
      priceWeekend: priceWeekend ?? this.priceWeekend,
      priceHighSeason: priceHighSeason ?? this.priceHighSeason,
      commissionPercent: commissionPercent ?? this.commissionPercent,
      privateNotes: privateNotes ?? this.privateNotes,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (name.present) {
      map['name'] = Variable<String>(name.value);
    }
    if (location.present) {
      map['location'] = Variable<String>(location.value);
    }
    if (ownerName.present) {
      map['owner_name'] = Variable<String>(ownerName.value);
    }
    if (ownerContact.present) {
      map['owner_contact'] = Variable<String>(ownerContact.value);
    }
    if (isActive.present) {
      map['is_active'] = Variable<int>(isActive.value);
    }
    if (description.present) {
      map['description'] = Variable<String>(description.value);
    }
    if (uniqueSellingPoints.present) {
      map['unique_selling_points'] = Variable<String>(
        uniqueSellingPoints.value,
      );
    }
    if (amenities.present) {
      map['amenities'] = Variable<String>(amenities.value);
    }
    if (houseRules.present) {
      map['house_rules'] = Variable<String>(houseRules.value);
    }
    if (priceWeekday.present) {
      map['price_weekday'] = Variable<int>(priceWeekday.value);
    }
    if (priceWeekend.present) {
      map['price_weekend'] = Variable<int>(priceWeekend.value);
    }
    if (priceHighSeason.present) {
      map['price_high_season'] = Variable<int>(priceHighSeason.value);
    }
    if (commissionPercent.present) {
      map['commission_percent'] = Variable<double>(commissionPercent.value);
    }
    if (privateNotes.present) {
      map['private_notes'] = Variable<String>(privateNotes.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (updatedAt.present) {
      map['updated_at'] = Variable<int>(updatedAt.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('VillasCompanion(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('location: $location, ')
          ..write('ownerName: $ownerName, ')
          ..write('ownerContact: $ownerContact, ')
          ..write('isActive: $isActive, ')
          ..write('description: $description, ')
          ..write('uniqueSellingPoints: $uniqueSellingPoints, ')
          ..write('amenities: $amenities, ')
          ..write('houseRules: $houseRules, ')
          ..write('priceWeekday: $priceWeekday, ')
          ..write('priceWeekend: $priceWeekend, ')
          ..write('priceHighSeason: $priceHighSeason, ')
          ..write('commissionPercent: $commissionPercent, ')
          ..write('privateNotes: $privateNotes, ')
          ..write('createdAt: $createdAt, ')
          ..write('updatedAt: $updatedAt, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DatabaseAtV1 extends GeneratedDatabase {
  DatabaseAtV1(QueryExecutor e) : super(e);
  late final Villas villas = Villas(this);
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [villas];
  @override
  int get schemaVersion => 1;
}
