// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class Villas extends Table with TableInfo<Villas, VillasData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Villas(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> location = GeneratedColumn<String>(
    'location',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<String> ownerName = GeneratedColumn<String>(
    'owner_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<String> ownerContact = GeneratedColumn<String>(
    'owner_contact',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<int> isActive = GeneratedColumn<int>(
    'is_active',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1))',
    defaultValue: const CustomExpression('1'),
  );
  late final GeneratedColumn<String> description = GeneratedColumn<String>(
    'description',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<String> uniqueSellingPoints =
      GeneratedColumn<String>(
        'unique_selling_points',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NOT NULL DEFAULT \'[]\'',
        defaultValue: const CustomExpression('\'[]\''),
      );
  late final GeneratedColumn<String> amenities = GeneratedColumn<String>(
    'amenities',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'[]\'',
    defaultValue: const CustomExpression('\'[]\''),
  );
  late final GeneratedColumn<String> houseRules = GeneratedColumn<String>(
    'house_rules',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<int> priceWeekday = GeneratedColumn<int>(
    'price_weekday',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> priceWeekend = GeneratedColumn<int>(
    'price_weekend',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> priceHighSeason = GeneratedColumn<int>(
    'price_high_season',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<double> commissionPercent =
      GeneratedColumn<double>(
        'commission_percent',
        aliasedName,
        false,
        type: DriftSqlType.double,
        requiredDuringInsert: false,
        $customConstraints: 'NOT NULL DEFAULT 0.0',
        defaultValue: const CustomExpression('0.0'),
      );
  late final GeneratedColumn<String> privateNotes = GeneratedColumn<String>(
    'private_notes',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> updatedAt = GeneratedColumn<int>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    name,
    location,
    ownerName,
    ownerContact,
    isActive,
    description,
    uniqueSellingPoints,
    amenities,
    houseRules,
    priceWeekday,
    priceWeekend,
    priceHighSeason,
    commissionPercent,
    privateNotes,
    createdAt,
    updatedAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'villas';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  VillasData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return VillasData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      name: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}name'],
      )!,
      location: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}location'],
      )!,
      ownerName: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}owner_name'],
      )!,
      ownerContact: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}owner_contact'],
      )!,
      isActive: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}is_active'],
      )!,
      description: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}description'],
      )!,
      uniqueSellingPoints: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}unique_selling_points'],
      )!,
      amenities: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}amenities'],
      )!,
      houseRules: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}house_rules'],
      )!,
      priceWeekday: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}price_weekday'],
      )!,
      priceWeekend: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}price_weekend'],
      )!,
      priceHighSeason: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}price_high_season'],
      )!,
      commissionPercent: attachedDatabase.typeMapping.read(
        DriftSqlType.double,
        data['${effectivePrefix}commission_percent'],
      )!,
      privateNotes: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}private_notes'],
      )!,
      createdAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at'],
      )!,
      updatedAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}updated_at'],
      )!,
    );
  }

  @override
  Villas createAlias(String alias) {
    return Villas(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class VillasData extends DataClass implements Insertable<VillasData> {
  final String id;
  final String name;
  final String location;
  final String ownerName;
  final String ownerContact;
  final int isActive;
  final String description;
  final String uniqueSellingPoints;
  final String amenities;
  final String houseRules;
  final int priceWeekday;
  final int priceWeekend;
  final int priceHighSeason;
  final double commissionPercent;
  final String privateNotes;
  final int createdAt;
  final int updatedAt;
  const VillasData({
    required this.id,
    required this.name,
    required this.location,
    required this.ownerName,
    required this.ownerContact,
    required this.isActive,
    required this.description,
    required this.uniqueSellingPoints,
    required this.amenities,
    required this.houseRules,
    required this.priceWeekday,
    required this.priceWeekend,
    required this.priceHighSeason,
    required this.commissionPercent,
    required this.privateNotes,
    required this.createdAt,
    required this.updatedAt,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['name'] = Variable<String>(name);
    map['location'] = Variable<String>(location);
    map['owner_name'] = Variable<String>(ownerName);
    map['owner_contact'] = Variable<String>(ownerContact);
    map['is_active'] = Variable<int>(isActive);
    map['description'] = Variable<String>(description);
    map['unique_selling_points'] = Variable<String>(uniqueSellingPoints);
    map['amenities'] = Variable<String>(amenities);
    map['house_rules'] = Variable<String>(houseRules);
    map['price_weekday'] = Variable<int>(priceWeekday);
    map['price_weekend'] = Variable<int>(priceWeekend);
    map['price_high_season'] = Variable<int>(priceHighSeason);
    map['commission_percent'] = Variable<double>(commissionPercent);
    map['private_notes'] = Variable<String>(privateNotes);
    map['created_at'] = Variable<int>(createdAt);
    map['updated_at'] = Variable<int>(updatedAt);
    return map;
  }

  VillasCompanion toCompanion(bool nullToAbsent) {
    return VillasCompanion(
      id: Value(id),
      name: Value(name),
      location: Value(location),
      ownerName: Value(ownerName),
      ownerContact: Value(ownerContact),
      isActive: Value(isActive),
      description: Value(description),
      uniqueSellingPoints: Value(uniqueSellingPoints),
      amenities: Value(amenities),
      houseRules: Value(houseRules),
      priceWeekday: Value(priceWeekday),
      priceWeekend: Value(priceWeekend),
      priceHighSeason: Value(priceHighSeason),
      commissionPercent: Value(commissionPercent),
      privateNotes: Value(privateNotes),
      createdAt: Value(createdAt),
      updatedAt: Value(updatedAt),
    );
  }

  factory VillasData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return VillasData(
      id: serializer.fromJson<String>(json['id']),
      name: serializer.fromJson<String>(json['name']),
      location: serializer.fromJson<String>(json['location']),
      ownerName: serializer.fromJson<String>(json['ownerName']),
      ownerContact: serializer.fromJson<String>(json['ownerContact']),
      isActive: serializer.fromJson<int>(json['isActive']),
      description: serializer.fromJson<String>(json['description']),
      uniqueSellingPoints: serializer.fromJson<String>(
        json['uniqueSellingPoints'],
      ),
      amenities: serializer.fromJson<String>(json['amenities']),
      houseRules: serializer.fromJson<String>(json['houseRules']),
      priceWeekday: serializer.fromJson<int>(json['priceWeekday']),
      priceWeekend: serializer.fromJson<int>(json['priceWeekend']),
      priceHighSeason: serializer.fromJson<int>(json['priceHighSeason']),
      commissionPercent: serializer.fromJson<double>(json['commissionPercent']),
      privateNotes: serializer.fromJson<String>(json['privateNotes']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
      updatedAt: serializer.fromJson<int>(json['updatedAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'name': serializer.toJson<String>(name),
      'location': serializer.toJson<String>(location),
      'ownerName': serializer.toJson<String>(ownerName),
      'ownerContact': serializer.toJson<String>(ownerContact),
      'isActive': serializer.toJson<int>(isActive),
      'description': serializer.toJson<String>(description),
      'uniqueSellingPoints': serializer.toJson<String>(uniqueSellingPoints),
      'amenities': serializer.toJson<String>(amenities),
      'houseRules': serializer.toJson<String>(houseRules),
      'priceWeekday': serializer.toJson<int>(priceWeekday),
      'priceWeekend': serializer.toJson<int>(priceWeekend),
      'priceHighSeason': serializer.toJson<int>(priceHighSeason),
      'commissionPercent': serializer.toJson<double>(commissionPercent),
      'privateNotes': serializer.toJson<String>(privateNotes),
      'createdAt': serializer.toJson<int>(createdAt),
      'updatedAt': serializer.toJson<int>(updatedAt),
    };
  }

  VillasData copyWith({
    String? id,
    String? name,
    String? location,
    String? ownerName,
    String? ownerContact,
    int? isActive,
    String? description,
    String? uniqueSellingPoints,
    String? amenities,
    String? houseRules,
    int? priceWeekday,
    int? priceWeekend,
    int? priceHighSeason,
    double? commissionPercent,
    String? privateNotes,
    int? createdAt,
    int? updatedAt,
  }) => VillasData(
    id: id ?? this.id,
    name: name ?? this.name,
    location: location ?? this.location,
    ownerName: ownerName ?? this.ownerName,
    ownerContact: ownerContact ?? this.ownerContact,
    isActive: isActive ?? this.isActive,
    description: description ?? this.description,
    uniqueSellingPoints: uniqueSellingPoints ?? this.uniqueSellingPoints,
    amenities: amenities ?? this.amenities,
    houseRules: houseRules ?? this.houseRules,
    priceWeekday: priceWeekday ?? this.priceWeekday,
    priceWeekend: priceWeekend ?? this.priceWeekend,
    priceHighSeason: priceHighSeason ?? this.priceHighSeason,
    commissionPercent: commissionPercent ?? this.commissionPercent,
    privateNotes: privateNotes ?? this.privateNotes,
    createdAt: createdAt ?? this.createdAt,
    updatedAt: updatedAt ?? this.updatedAt,
  );
  VillasData copyWithCompanion(VillasCompanion data) {
    return VillasData(
      id: data.id.present ? data.id.value : this.id,
      name: data.name.present ? data.name.value : this.name,
      location: data.location.present ? data.location.value : this.location,
      ownerName: data.ownerName.present ? data.ownerName.value : this.ownerName,
      ownerContact: data.ownerContact.present
          ? data.ownerContact.value
          : this.ownerContact,
      isActive: data.isActive.present ? data.isActive.value : this.isActive,
      description: data.description.present
          ? data.description.value
          : this.description,
      uniqueSellingPoints: data.uniqueSellingPoints.present
          ? data.uniqueSellingPoints.value
          : this.uniqueSellingPoints,
      amenities: data.amenities.present ? data.amenities.value : this.amenities,
      houseRules: data.houseRules.present
          ? data.houseRules.value
          : this.houseRules,
      priceWeekday: data.priceWeekday.present
          ? data.priceWeekday.value
          : this.priceWeekday,
      priceWeekend: data.priceWeekend.present
          ? data.priceWeekend.value
          : this.priceWeekend,
      priceHighSeason: data.priceHighSeason.present
          ? data.priceHighSeason.value
          : this.priceHighSeason,
      commissionPercent: data.commissionPercent.present
          ? data.commissionPercent.value
          : this.commissionPercent,
      privateNotes: data.privateNotes.present
          ? data.privateNotes.value
          : this.privateNotes,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
      updatedAt: data.updatedAt.present ? data.updatedAt.value : this.updatedAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('VillasData(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('location: $location, ')
          ..write('ownerName: $ownerName, ')
          ..write('ownerContact: $ownerContact, ')
          ..write('isActive: $isActive, ')
          ..write('description: $description, ')
          ..write('uniqueSellingPoints: $uniqueSellingPoints, ')
          ..write('amenities: $amenities, ')
          ..write('houseRules: $houseRules, ')
          ..write('priceWeekday: $priceWeekday, ')
          ..write('priceWeekend: $priceWeekend, ')
          ..write('priceHighSeason: $priceHighSeason, ')
          ..write('commissionPercent: $commissionPercent, ')
          ..write('privateNotes: $privateNotes, ')
          ..write('createdAt: $createdAt, ')
          ..write('updatedAt: $updatedAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    name,
    location,
    ownerName,
    ownerContact,
    isActive,
    description,
    uniqueSellingPoints,
    amenities,
    houseRules,
    priceWeekday,
    priceWeekend,
    priceHighSeason,
    commissionPercent,
    privateNotes,
    createdAt,
    updatedAt,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is VillasData &&
          other.id == this.id &&
          other.name == this.name &&
          other.location == this.location &&
          other.ownerName == this.ownerName &&
          other.ownerContact == this.ownerContact &&
          other.isActive == this.isActive &&
          other.description == this.description &&
          other.uniqueSellingPoints == this.uniqueSellingPoints &&
          other.amenities == this.amenities &&
          other.houseRules == this.houseRules &&
          other.priceWeekday == this.priceWeekday &&
          other.priceWeekend == this.priceWeekend &&
          other.priceHighSeason == this.priceHighSeason &&
          other.commissionPercent == this.commissionPercent &&
          other.privateNotes == this.privateNotes &&
          other.createdAt == this.createdAt &&
          other.updatedAt == this.updatedAt);
}

class VillasCompanion extends UpdateCompanion<VillasData> {
  final Value<String> id;
  final Value<String> name;
  final Value<String> location;
  final Value<String> ownerName;
  final Value<String> ownerContact;
  final Value<int> isActive;
  final Value<String> description;
  final Value<String> uniqueSellingPoints;
  final Value<String> amenities;
  final Value<String> houseRules;
  final Value<int> priceWeekday;
  final Value<int> priceWeekend;
  final Value<int> priceHighSeason;
  final Value<double> commissionPercent;
  final Value<String> privateNotes;
  final Value<int> createdAt;
  final Value<int> updatedAt;
  final Value<int> rowid;
  const VillasCompanion({
    this.id = const Value.absent(),
    this.name = const Value.absent(),
    this.location = const Value.absent(),
    this.ownerName = const Value.absent(),
    this.ownerContact = const Value.absent(),
    this.isActive = const Value.absent(),
    this.description = const Value.absent(),
    this.uniqueSellingPoints = const Value.absent(),
    this.amenities = const Value.absent(),
    this.houseRules = const Value.absent(),
    this.priceWeekday = const Value.absent(),
    this.priceWeekend = const Value.absent(),
    this.priceHighSeason = const Value.absent(),
    this.commissionPercent = const Value.absent(),
    this.privateNotes = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.updatedAt = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  VillasCompanion.insert({
    required String id,
    required String name,
    this.location = const Value.absent(),
    this.ownerName = const Value.absent(),
    this.ownerContact = const Value.absent(),
    this.isActive = const Value.absent(),
    this.description = const Value.absent(),
    this.uniqueSellingPoints = const Value.absent(),
    this.amenities = const Value.absent(),
    this.houseRules = const Value.absent(),
    this.priceWeekday = const Value.absent(),
    this.priceWeekend = const Value.absent(),
    this.priceHighSeason = const Value.absent(),
    this.commissionPercent = const Value.absent(),
    this.privateNotes = const Value.absent(),
    required int createdAt,
    required int updatedAt,
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       name = Value(name),
       createdAt = Value(createdAt),
       updatedAt = Value(updatedAt);
  static Insertable<VillasData> custom({
    Expression<String>? id,
    Expression<String>? name,
    Expression<String>? location,
    Expression<String>? ownerName,
    Expression<String>? ownerContact,
    Expression<int>? isActive,
    Expression<String>? description,
    Expression<String>? uniqueSellingPoints,
    Expression<String>? amenities,
    Expression<String>? houseRules,
    Expression<int>? priceWeekday,
    Expression<int>? priceWeekend,
    Expression<int>? priceHighSeason,
    Expression<double>? commissionPercent,
    Expression<String>? privateNotes,
    Expression<int>? createdAt,
    Expression<int>? updatedAt,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (location != null) 'location': location,
      if (ownerName != null) 'owner_name': ownerName,
      if (ownerContact != null) 'owner_contact': ownerContact,
      if (isActive != null) 'is_active': isActive,
      if (description != null) 'description': description,
      if (uniqueSellingPoints != null)
        'unique_selling_points': uniqueSellingPoints,
      if (amenities != null) 'amenities': amenities,
      if (houseRules != null) 'house_rules': houseRules,
      if (priceWeekday != null) 'price_weekday': priceWeekday,
      if (priceWeekend != null) 'price_weekend': priceWeekend,
      if (priceHighSeason != null) 'price_high_season': priceHighSeason,
      if (commissionPercent != null) 'commission_percent': commissionPercent,
      if (privateNotes != null) 'private_notes': privateNotes,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
      if (rowid != null) 'rowid': rowid,
    });
  }

  VillasCompanion copyWith({
    Value<String>? id,
    Value<String>? name,
    Value<String>? location,
    Value<String>? ownerName,
    Value<String>? ownerContact,
    Value<int>? isActive,
    Value<String>? description,
    Value<String>? uniqueSellingPoints,
    Value<String>? amenities,
    Value<String>? houseRules,
    Value<int>? priceWeekday,
    Value<int>? priceWeekend,
    Value<int>? priceHighSeason,
    Value<double>? commissionPercent,
    Value<String>? privateNotes,
    Value<int>? createdAt,
    Value<int>? updatedAt,
    Value<int>? rowid,
  }) {
    return VillasCompanion(
      id: id ?? this.id,
      name: name ?? this.name,
      location: location ?? this.location,
      ownerName: ownerName ?? this.ownerName,
      ownerContact: ownerContact ?? this.ownerContact,
      isActive: isActive ?? this.isActive,
      description: description ?? this.description,
      uniqueSellingPoints: uniqueSellingPoints ?? this.uniqueSellingPoints,
      amenities: amenities ?? this.amenities,
      houseRules: houseRules ?? this.houseRules,
      priceWeekday: priceWeekday ?? this.priceWeekday,
      priceWeekend: priceWeekend ?? this.priceWeekend,
      priceHighSeason: priceHighSeason ?? this.priceHighSeason,
      commissionPercent: commissionPercent ?? this.commissionPercent,
      privateNotes: privateNotes ?? this.privateNotes,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (name.present) {
      map['name'] = Variable<String>(name.value);
    }
    if (location.present) {
      map['location'] = Variable<String>(location.value);
    }
    if (ownerName.present) {
      map['owner_name'] = Variable<String>(ownerName.value);
    }
    if (ownerContact.present) {
      map['owner_contact'] = Variable<String>(ownerContact.value);
    }
    if (isActive.present) {
      map['is_active'] = Variable<int>(isActive.value);
    }
    if (description.present) {
      map['description'] = Variable<String>(description.value);
    }
    if (uniqueSellingPoints.present) {
      map['unique_selling_points'] = Variable<String>(
        uniqueSellingPoints.value,
      );
    }
    if (amenities.present) {
      map['amenities'] = Variable<String>(amenities.value);
    }
    if (houseRules.present) {
      map['house_rules'] = Variable<String>(houseRules.value);
    }
    if (priceWeekday.present) {
      map['price_weekday'] = Variable<int>(priceWeekday.value);
    }
    if (priceWeekend.present) {
      map['price_weekend'] = Variable<int>(priceWeekend.value);
    }
    if (priceHighSeason.present) {
      map['price_high_season'] = Variable<int>(priceHighSeason.value);
    }
    if (commissionPercent.present) {
      map['commission_percent'] = Variable<double>(commissionPercent.value);
    }
    if (privateNotes.present) {
      map['private_notes'] = Variable<String>(privateNotes.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (updatedAt.present) {
      map['updated_at'] = Variable<int>(updatedAt.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('VillasCompanion(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('location: $location, ')
          ..write('ownerName: $ownerName, ')
          ..write('ownerContact: $ownerContact, ')
          ..write('isActive: $isActive, ')
          ..write('description: $description, ')
          ..write('uniqueSellingPoints: $uniqueSellingPoints, ')
          ..write('amenities: $amenities, ')
          ..write('houseRules: $houseRules, ')
          ..write('priceWeekday: $priceWeekday, ')
          ..write('priceWeekend: $priceWeekend, ')
          ..write('priceHighSeason: $priceHighSeason, ')
          ..write('commissionPercent: $commissionPercent, ')
          ..write('privateNotes: $privateNotes, ')
          ..write('createdAt: $createdAt, ')
          ..write('updatedAt: $updatedAt, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class VillaPhotos extends Table with TableInfo<VillaPhotos, VillaPhotosData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  VillaPhotos(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> villaId = GeneratedColumn<String>(
    'villa_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> filePath = GeneratedColumn<String>(
    'file_path',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> sortOrder = GeneratedColumn<int>(
    'sort_order',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  @override
  List<GeneratedColumn> get $columns => [id, villaId, filePath, sortOrder];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'villa_photos';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  VillaPhotosData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return VillaPhotosData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      villaId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}villa_id'],
      )!,
      filePath: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}file_path'],
      )!,
      sortOrder: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}sort_order'],
      )!,
    );
  }

  @override
  VillaPhotos createAlias(String alias) {
    return VillaPhotos(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class VillaPhotosData extends DataClass implements Insertable<VillaPhotosData> {
  final String id;
  final String villaId;
  final String filePath;
  final int sortOrder;
  const VillaPhotosData({
    required this.id,
    required this.villaId,
    required this.filePath,
    required this.sortOrder,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['villa_id'] = Variable<String>(villaId);
    map['file_path'] = Variable<String>(filePath);
    map['sort_order'] = Variable<int>(sortOrder);
    return map;
  }

  VillaPhotosCompanion toCompanion(bool nullToAbsent) {
    return VillaPhotosCompanion(
      id: Value(id),
      villaId: Value(villaId),
      filePath: Value(filePath),
      sortOrder: Value(sortOrder),
    );
  }

  factory VillaPhotosData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return VillaPhotosData(
      id: serializer.fromJson<String>(json['id']),
      villaId: serializer.fromJson<String>(json['villaId']),
      filePath: serializer.fromJson<String>(json['filePath']),
      sortOrder: serializer.fromJson<int>(json['sortOrder']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'villaId': serializer.toJson<String>(villaId),
      'filePath': serializer.toJson<String>(filePath),
      'sortOrder': serializer.toJson<int>(sortOrder),
    };
  }

  VillaPhotosData copyWith({
    String? id,
    String? villaId,
    String? filePath,
    int? sortOrder,
  }) => VillaPhotosData(
    id: id ?? this.id,
    villaId: villaId ?? this.villaId,
    filePath: filePath ?? this.filePath,
    sortOrder: sortOrder ?? this.sortOrder,
  );
  VillaPhotosData copyWithCompanion(VillaPhotosCompanion data) {
    return VillaPhotosData(
      id: data.id.present ? data.id.value : this.id,
      villaId: data.villaId.present ? data.villaId.value : this.villaId,
      filePath: data.filePath.present ? data.filePath.value : this.filePath,
      sortOrder: data.sortOrder.present ? data.sortOrder.value : this.sortOrder,
    );
  }

  @override
  String toString() {
    return (StringBuffer('VillaPhotosData(')
          ..write('id: $id, ')
          ..write('villaId: $villaId, ')
          ..write('filePath: $filePath, ')
          ..write('sortOrder: $sortOrder')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, villaId, filePath, sortOrder);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is VillaPhotosData &&
          other.id == this.id &&
          other.villaId == this.villaId &&
          other.filePath == this.filePath &&
          other.sortOrder == this.sortOrder);
}

class VillaPhotosCompanion extends UpdateCompanion<VillaPhotosData> {
  final Value<String> id;
  final Value<String> villaId;
  final Value<String> filePath;
  final Value<int> sortOrder;
  final Value<int> rowid;
  const VillaPhotosCompanion({
    this.id = const Value.absent(),
    this.villaId = const Value.absent(),
    this.filePath = const Value.absent(),
    this.sortOrder = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  VillaPhotosCompanion.insert({
    required String id,
    required String villaId,
    required String filePath,
    this.sortOrder = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       villaId = Value(villaId),
       filePath = Value(filePath);
  static Insertable<VillaPhotosData> custom({
    Expression<String>? id,
    Expression<String>? villaId,
    Expression<String>? filePath,
    Expression<int>? sortOrder,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (villaId != null) 'villa_id': villaId,
      if (filePath != null) 'file_path': filePath,
      if (sortOrder != null) 'sort_order': sortOrder,
      if (rowid != null) 'rowid': rowid,
    });
  }

  VillaPhotosCompanion copyWith({
    Value<String>? id,
    Value<String>? villaId,
    Value<String>? filePath,
    Value<int>? sortOrder,
    Value<int>? rowid,
  }) {
    return VillaPhotosCompanion(
      id: id ?? this.id,
      villaId: villaId ?? this.villaId,
      filePath: filePath ?? this.filePath,
      sortOrder: sortOrder ?? this.sortOrder,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (villaId.present) {
      map['villa_id'] = Variable<String>(villaId.value);
    }
    if (filePath.present) {
      map['file_path'] = Variable<String>(filePath.value);
    }
    if (sortOrder.present) {
      map['sort_order'] = Variable<int>(sortOrder.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('VillaPhotosCompanion(')
          ..write('id: $id, ')
          ..write('villaId: $villaId, ')
          ..write('filePath: $filePath, ')
          ..write('sortOrder: $sortOrder, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class VillaFaqs extends Table with TableInfo<VillaFaqs, VillaFaqsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  VillaFaqs(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> villaId = GeneratedColumn<String>(
    'villa_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> question = GeneratedColumn<String>(
    'question',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> answer = GeneratedColumn<String>(
    'answer',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [id, villaId, question, answer];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'villa_faqs';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  VillaFaqsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return VillaFaqsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      villaId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}villa_id'],
      )!,
      question: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}question'],
      )!,
      answer: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}answer'],
      )!,
    );
  }

  @override
  VillaFaqs createAlias(String alias) {
    return VillaFaqs(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class VillaFaqsData extends DataClass implements Insertable<VillaFaqsData> {
  final String id;
  final String villaId;
  final String question;
  final String answer;
  const VillaFaqsData({
    required this.id,
    required this.villaId,
    required this.question,
    required this.answer,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['villa_id'] = Variable<String>(villaId);
    map['question'] = Variable<String>(question);
    map['answer'] = Variable<String>(answer);
    return map;
  }

  VillaFaqsCompanion toCompanion(bool nullToAbsent) {
    return VillaFaqsCompanion(
      id: Value(id),
      villaId: Value(villaId),
      question: Value(question),
      answer: Value(answer),
    );
  }

  factory VillaFaqsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return VillaFaqsData(
      id: serializer.fromJson<String>(json['id']),
      villaId: serializer.fromJson<String>(json['villaId']),
      question: serializer.fromJson<String>(json['question']),
      answer: serializer.fromJson<String>(json['answer']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'villaId': serializer.toJson<String>(villaId),
      'question': serializer.toJson<String>(question),
      'answer': serializer.toJson<String>(answer),
    };
  }

  VillaFaqsData copyWith({
    String? id,
    String? villaId,
    String? question,
    String? answer,
  }) => VillaFaqsData(
    id: id ?? this.id,
    villaId: villaId ?? this.villaId,
    question: question ?? this.question,
    answer: answer ?? this.answer,
  );
  VillaFaqsData copyWithCompanion(VillaFaqsCompanion data) {
    return VillaFaqsData(
      id: data.id.present ? data.id.value : this.id,
      villaId: data.villaId.present ? data.villaId.value : this.villaId,
      question: data.question.present ? data.question.value : this.question,
      answer: data.answer.present ? data.answer.value : this.answer,
    );
  }

  @override
  String toString() {
    return (StringBuffer('VillaFaqsData(')
          ..write('id: $id, ')
          ..write('villaId: $villaId, ')
          ..write('question: $question, ')
          ..write('answer: $answer')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, villaId, question, answer);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is VillaFaqsData &&
          other.id == this.id &&
          other.villaId == this.villaId &&
          other.question == this.question &&
          other.answer == this.answer);
}

class VillaFaqsCompanion extends UpdateCompanion<VillaFaqsData> {
  final Value<String> id;
  final Value<String> villaId;
  final Value<String> question;
  final Value<String> answer;
  final Value<int> rowid;
  const VillaFaqsCompanion({
    this.id = const Value.absent(),
    this.villaId = const Value.absent(),
    this.question = const Value.absent(),
    this.answer = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  VillaFaqsCompanion.insert({
    required String id,
    required String villaId,
    required String question,
    required String answer,
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       villaId = Value(villaId),
       question = Value(question),
       answer = Value(answer);
  static Insertable<VillaFaqsData> custom({
    Expression<String>? id,
    Expression<String>? villaId,
    Expression<String>? question,
    Expression<String>? answer,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (villaId != null) 'villa_id': villaId,
      if (question != null) 'question': question,
      if (answer != null) 'answer': answer,
      if (rowid != null) 'rowid': rowid,
    });
  }

  VillaFaqsCompanion copyWith({
    Value<String>? id,
    Value<String>? villaId,
    Value<String>? question,
    Value<String>? answer,
    Value<int>? rowid,
  }) {
    return VillaFaqsCompanion(
      id: id ?? this.id,
      villaId: villaId ?? this.villaId,
      question: question ?? this.question,
      answer: answer ?? this.answer,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (villaId.present) {
      map['villa_id'] = Variable<String>(villaId.value);
    }
    if (question.present) {
      map['question'] = Variable<String>(question.value);
    }
    if (answer.present) {
      map['answer'] = Variable<String>(answer.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('VillaFaqsCompanion(')
          ..write('id: $id, ')
          ..write('villaId: $villaId, ')
          ..write('question: $question, ')
          ..write('answer: $answer, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class Bookings extends Table with TableInfo<Bookings, BookingsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Bookings(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> villaId = GeneratedColumn<String>(
    'villa_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> guestName = GeneratedColumn<String>(
    'guest_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> guestContact = GeneratedColumn<String>(
    'guest_contact',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<int> checkIn = GeneratedColumn<int>(
    'check_in',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> checkOut = GeneratedColumn<int>(
    'check_out',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> pricePerNightSnapshot = GeneratedColumn<int>(
    'price_per_night_snapshot',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'confirmed\'',
    defaultValue: const CustomExpression('\'confirmed\''),
  );
  late final GeneratedColumn<String> notes = GeneratedColumn<String>(
    'notes',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    villaId,
    guestName,
    guestContact,
    checkIn,
    checkOut,
    pricePerNightSnapshot,
    status,
    notes,
    createdAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'bookings';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  BookingsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return BookingsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      villaId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}villa_id'],
      )!,
      guestName: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}guest_name'],
      )!,
      guestContact: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}guest_contact'],
      )!,
      checkIn: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}check_in'],
      )!,
      checkOut: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}check_out'],
      )!,
      pricePerNightSnapshot: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}price_per_night_snapshot'],
      )!,
      status: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}status'],
      )!,
      notes: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}notes'],
      )!,
      createdAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at'],
      )!,
    );
  }

  @override
  Bookings createAlias(String alias) {
    return Bookings(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class BookingsData extends DataClass implements Insertable<BookingsData> {
  final String id;
  final String villaId;
  final String guestName;
  final String guestContact;
  final int checkIn;
  final int checkOut;
  final int pricePerNightSnapshot;
  final String status;
  final String notes;
  final int createdAt;
  const BookingsData({
    required this.id,
    required this.villaId,
    required this.guestName,
    required this.guestContact,
    required this.checkIn,
    required this.checkOut,
    required this.pricePerNightSnapshot,
    required this.status,
    required this.notes,
    required this.createdAt,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['villa_id'] = Variable<String>(villaId);
    map['guest_name'] = Variable<String>(guestName);
    map['guest_contact'] = Variable<String>(guestContact);
    map['check_in'] = Variable<int>(checkIn);
    map['check_out'] = Variable<int>(checkOut);
    map['price_per_night_snapshot'] = Variable<int>(pricePerNightSnapshot);
    map['status'] = Variable<String>(status);
    map['notes'] = Variable<String>(notes);
    map['created_at'] = Variable<int>(createdAt);
    return map;
  }

  BookingsCompanion toCompanion(bool nullToAbsent) {
    return BookingsCompanion(
      id: Value(id),
      villaId: Value(villaId),
      guestName: Value(guestName),
      guestContact: Value(guestContact),
      checkIn: Value(checkIn),
      checkOut: Value(checkOut),
      pricePerNightSnapshot: Value(pricePerNightSnapshot),
      status: Value(status),
      notes: Value(notes),
      createdAt: Value(createdAt),
    );
  }

  factory BookingsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return BookingsData(
      id: serializer.fromJson<String>(json['id']),
      villaId: serializer.fromJson<String>(json['villaId']),
      guestName: serializer.fromJson<String>(json['guestName']),
      guestContact: serializer.fromJson<String>(json['guestContact']),
      checkIn: serializer.fromJson<int>(json['checkIn']),
      checkOut: serializer.fromJson<int>(json['checkOut']),
      pricePerNightSnapshot: serializer.fromJson<int>(
        json['pricePerNightSnapshot'],
      ),
      status: serializer.fromJson<String>(json['status']),
      notes: serializer.fromJson<String>(json['notes']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'villaId': serializer.toJson<String>(villaId),
      'guestName': serializer.toJson<String>(guestName),
      'guestContact': serializer.toJson<String>(guestContact),
      'checkIn': serializer.toJson<int>(checkIn),
      'checkOut': serializer.toJson<int>(checkOut),
      'pricePerNightSnapshot': serializer.toJson<int>(pricePerNightSnapshot),
      'status': serializer.toJson<String>(status),
      'notes': serializer.toJson<String>(notes),
      'createdAt': serializer.toJson<int>(createdAt),
    };
  }

  BookingsData copyWith({
    String? id,
    String? villaId,
    String? guestName,
    String? guestContact,
    int? checkIn,
    int? checkOut,
    int? pricePerNightSnapshot,
    String? status,
    String? notes,
    int? createdAt,
  }) => BookingsData(
    id: id ?? this.id,
    villaId: villaId ?? this.villaId,
    guestName: guestName ?? this.guestName,
    guestContact: guestContact ?? this.guestContact,
    checkIn: checkIn ?? this.checkIn,
    checkOut: checkOut ?? this.checkOut,
    pricePerNightSnapshot: pricePerNightSnapshot ?? this.pricePerNightSnapshot,
    status: status ?? this.status,
    notes: notes ?? this.notes,
    createdAt: createdAt ?? this.createdAt,
  );
  BookingsData copyWithCompanion(BookingsCompanion data) {
    return BookingsData(
      id: data.id.present ? data.id.value : this.id,
      villaId: data.villaId.present ? data.villaId.value : this.villaId,
      guestName: data.guestName.present ? data.guestName.value : this.guestName,
      guestContact: data.guestContact.present
          ? data.guestContact.value
          : this.guestContact,
      checkIn: data.checkIn.present ? data.checkIn.value : this.checkIn,
      checkOut: data.checkOut.present ? data.checkOut.value : this.checkOut,
      pricePerNightSnapshot: data.pricePerNightSnapshot.present
          ? data.pricePerNightSnapshot.value
          : this.pricePerNightSnapshot,
      status: data.status.present ? data.status.value : this.status,
      notes: data.notes.present ? data.notes.value : this.notes,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('BookingsData(')
          ..write('id: $id, ')
          ..write('villaId: $villaId, ')
          ..write('guestName: $guestName, ')
          ..write('guestContact: $guestContact, ')
          ..write('checkIn: $checkIn, ')
          ..write('checkOut: $checkOut, ')
          ..write('pricePerNightSnapshot: $pricePerNightSnapshot, ')
          ..write('status: $status, ')
          ..write('notes: $notes, ')
          ..write('createdAt: $createdAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    villaId,
    guestName,
    guestContact,
    checkIn,
    checkOut,
    pricePerNightSnapshot,
    status,
    notes,
    createdAt,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is BookingsData &&
          other.id == this.id &&
          other.villaId == this.villaId &&
          other.guestName == this.guestName &&
          other.guestContact == this.guestContact &&
          other.checkIn == this.checkIn &&
          other.checkOut == this.checkOut &&
          other.pricePerNightSnapshot == this.pricePerNightSnapshot &&
          other.status == this.status &&
          other.notes == this.notes &&
          other.createdAt == this.createdAt);
}

class BookingsCompanion extends UpdateCompanion<BookingsData> {
  final Value<String> id;
  final Value<String> villaId;
  final Value<String> guestName;
  final Value<String> guestContact;
  final Value<int> checkIn;
  final Value<int> checkOut;
  final Value<int> pricePerNightSnapshot;
  final Value<String> status;
  final Value<String> notes;
  final Value<int> createdAt;
  final Value<int> rowid;
  const BookingsCompanion({
    this.id = const Value.absent(),
    this.villaId = const Value.absent(),
    this.guestName = const Value.absent(),
    this.guestContact = const Value.absent(),
    this.checkIn = const Value.absent(),
    this.checkOut = const Value.absent(),
    this.pricePerNightSnapshot = const Value.absent(),
    this.status = const Value.absent(),
    this.notes = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  BookingsCompanion.insert({
    required String id,
    required String villaId,
    required String guestName,
    this.guestContact = const Value.absent(),
    required int checkIn,
    required int checkOut,
    this.pricePerNightSnapshot = const Value.absent(),
    this.status = const Value.absent(),
    this.notes = const Value.absent(),
    required int createdAt,
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       villaId = Value(villaId),
       guestName = Value(guestName),
       checkIn = Value(checkIn),
       checkOut = Value(checkOut),
       createdAt = Value(createdAt);
  static Insertable<BookingsData> custom({
    Expression<String>? id,
    Expression<String>? villaId,
    Expression<String>? guestName,
    Expression<String>? guestContact,
    Expression<int>? checkIn,
    Expression<int>? checkOut,
    Expression<int>? pricePerNightSnapshot,
    Expression<String>? status,
    Expression<String>? notes,
    Expression<int>? createdAt,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (villaId != null) 'villa_id': villaId,
      if (guestName != null) 'guest_name': guestName,
      if (guestContact != null) 'guest_contact': guestContact,
      if (checkIn != null) 'check_in': checkIn,
      if (checkOut != null) 'check_out': checkOut,
      if (pricePerNightSnapshot != null)
        'price_per_night_snapshot': pricePerNightSnapshot,
      if (status != null) 'status': status,
      if (notes != null) 'notes': notes,
      if (createdAt != null) 'created_at': createdAt,
      if (rowid != null) 'rowid': rowid,
    });
  }

  BookingsCompanion copyWith({
    Value<String>? id,
    Value<String>? villaId,
    Value<String>? guestName,
    Value<String>? guestContact,
    Value<int>? checkIn,
    Value<int>? checkOut,
    Value<int>? pricePerNightSnapshot,
    Value<String>? status,
    Value<String>? notes,
    Value<int>? createdAt,
    Value<int>? rowid,
  }) {
    return BookingsCompanion(
      id: id ?? this.id,
      villaId: villaId ?? this.villaId,
      guestName: guestName ?? this.guestName,
      guestContact: guestContact ?? this.guestContact,
      checkIn: checkIn ?? this.checkIn,
      checkOut: checkOut ?? this.checkOut,
      pricePerNightSnapshot:
          pricePerNightSnapshot ?? this.pricePerNightSnapshot,
      status: status ?? this.status,
      notes: notes ?? this.notes,
      createdAt: createdAt ?? this.createdAt,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (villaId.present) {
      map['villa_id'] = Variable<String>(villaId.value);
    }
    if (guestName.present) {
      map['guest_name'] = Variable<String>(guestName.value);
    }
    if (guestContact.present) {
      map['guest_contact'] = Variable<String>(guestContact.value);
    }
    if (checkIn.present) {
      map['check_in'] = Variable<int>(checkIn.value);
    }
    if (checkOut.present) {
      map['check_out'] = Variable<int>(checkOut.value);
    }
    if (pricePerNightSnapshot.present) {
      map['price_per_night_snapshot'] = Variable<int>(
        pricePerNightSnapshot.value,
      );
    }
    if (status.present) {
      map['status'] = Variable<String>(status.value);
    }
    if (notes.present) {
      map['notes'] = Variable<String>(notes.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('BookingsCompanion(')
          ..write('id: $id, ')
          ..write('villaId: $villaId, ')
          ..write('guestName: $guestName, ')
          ..write('guestContact: $guestContact, ')
          ..write('checkIn: $checkIn, ')
          ..write('checkOut: $checkOut, ')
          ..write('pricePerNightSnapshot: $pricePerNightSnapshot, ')
          ..write('status: $status, ')
          ..write('notes: $notes, ')
          ..write('createdAt: $createdAt, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DatabaseAtV3 extends GeneratedDatabase {
  DatabaseAtV3(QueryExecutor e) : super(e);
  late final Villas villas = Villas(this);
  late final VillaPhotos villaPhotos = VillaPhotos(this);
  late final VillaFaqs villaFaqs = VillaFaqs(this);
  late final Bookings bookings = Bookings(this);
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    villas,
    villaPhotos,
    villaFaqs,
    bookings,
  ];
  @override
  int get schemaVersion => 3;
}
